version: '3'

services:
  webapp:
    environment:
      - DEBUG=1
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ~/.m2:/root/.m2
      - ../:/app
    command: /app/docker/scripts/run.sh
    ports:
      - 8080:8080
      - 5005:5005
